services:
  travel-booking-backend:
    container_name: "travel-booking-backend"
    build: .
    environment:
      - ConnectionStrings__StoreContext=Host=travel-booking-db;Username=postgres;Password=postgres;Database=travelbooking
    volumes:
      - misc_data:/root/.aspnet
    expose:
      - 5000
    depends_on:
      - travel-booking-db
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://travel-booking-backend:5000/api/health || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.travel-backend-api.entrypoints=websecure"
      - "traefik.http.routers.travel-backend-api.rule=Host(`travel.foxelyss.ru`) && PathPrefix(`/api/`)"
      - "traefik.http.services.travel-backend-api.loadbalancer.server.port=5000"
      
      - "traefik.http.routers.travel-backend-api.middlewares=travel-backend-headers"
      - "traefik.http.middlewares.travel-backend-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.travel-backend-headers.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.travel-backend-headers.headers.accesscontrolalloworiginlist=https://travel.foxelyss.ru"
      - "traefik.http.middlewares.travel-backend-headers.headers.addvaryheader=true"
      - "traefik.http.middlewares.travel-backend-headers.headers.customResponseHeaders.Access-Control-Allow-Origin=https://travel.foxelyss.ru"

    networks:
      - travel
      - mega-main

  travel-booking-db:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=travelbooking
    volumes:
      - db_data:/var/lib/postgresql/
    expose:
      - 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    restart: unless-stopped
    networks:
      - travel

volumes:
  misc_data:
  db_data:


networks:
  travel:
  mega-main:
    external: true
    name: mega-network
