when:
  - event: manual
    branch: main

steps:
  - name: build-image
    image: docker
    commands:
      - cd travel-booking
      - docker compose build
      - docker compose up -d
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
