when:
  - event: manual
    branch: main

steps:
  - name: build-image
    image: docker
    commands:
      - docker compose -f deploy-compose.yaml build
      - docker compose -f deploy-compose.yaml up -d 
      - docker compose -f deploy-compose.yaml logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
